### ISSUE TITLE
Wrong kind of system capture

### ISSUE THREAD

**Issue by System-Dave** [spatialaudio/jackclient-python#110]
Maybe I am not understanding this correctly, but through python system capture is strictly through my headset's mic. Through QJackCTL, however, I have the ability to change the interface to Stereo mix and get my actual desktop audio. Is there something I am missing or does this library not include the ability to change interfaces like QJackCTL?

**Comment by HaHeho** [comment]
What you do with QJackCtl is starting the Jack server with a specific set of parameters, e.g. the used audio interface.

This API only provides you to setup Jack clients.

If you create a client an no Jack server is running, then one will be started with a default set of parameters (see the Jack documentation on how this could be customized depending on the system you're using). Alternatively, you can start the Jack server with exactly the parameters you need beforehand, e.g QJackCtl or terminal.

**Comment by mgeier** [comment]
See also #90 where I suggested that this module should only do "client" things, and "server" things should be by done a different module (either an existing one or a newly created one).
