### ISSUE TITLE
Use RingBuffer in midi_monitor.py example

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/jackclient-python#15]
Printing to the terminal isn't allowed in the process callback.
The data should be transferred to a non-realtime thread for printing.

This could also be a nice usage example for the `RingBuffer`.

**Comment by amstan** [comment]
Would Queue be an easier thing to use in python? Not sure what the timing implications are, but i think one can get a nonblocking version of it.

I know we have it (and my project actually needs it since it uses ringbuffers in the C portion), but Queue might be a better choice if you want to move structured data.

**Comment by mgeier** [comment]
> but i think one can get a nonblocking version of it

I think that's the point, as far as I understand, Python's [queue module](https://docs.python.org/3/library/queue.html) uses locking.

Where would we get a non-blocking queue?

> Queue might be a better choice if you want to move structured data.

Sure, but that's why I think it would be a good usage example, because there we could show how to use a `RingBuffer` with data items which are larger than a byte.

BTW, I don't know yet how to do that ...

**Comment by amstan** [comment]
> Sure, but that's why I think it would be a good usage example, because there we could show how to use a RingBuffer with data items which are larger than a byte.

Well, I implemented both examples for you.

As I predicted, the ringbuffer one is a lot bigger and uglier. I don't think there are many advantages on using that one (besides the fact that maybe it has a leaner implementation? but who cares, we're using python anyway). I also had to use struct to pack and unpack the time offsets and lengths for the packets.

**Comment by amstan** [comment]
Ringbuffers might be better suited to move audio data around (since individual samples don't really need to be time labeled) and everything (bigger chunks too) can be kept in buffer form.

**Comment by mgeier** [comment]
Thanks for the example implementations, that's really interesting!

Python's built-in `Queue` uses locks, right?
If yes, it's as bad as directly using `print()` in the process callback, so we don't gain anything with `Queue`.

It is indeed much more complicated than I imagined to use the `jack.RingBuffer` for this.

Due to an apparent lack of a blocking "read" function, we cannot wait on the `RingBuffer` (on the non-realtime side), which makes the code even worse.

In the light of this I think it's best to just keep the `print()` calls as they are and add a comment that this is actually bad practice and shouldn't be used in real code.

In the future we might find a more meaningful example which sends audio data over a `RingBuffer`.

**Comment by amstan** [comment]
> Python's built-in Queue uses locks, right?
If yes, it's as bad as directly using print() in the process callback, so we don't gain anything with Queue.

It probably does use locks, but it's non-blocking (the stuff inside process shouldn't wait for a long time all the sudden). So it should be fine.

I do think it's better to use Queue than no Queue and just print.

**Comment by mgeier** [comment]
I had a quick look at the CPython source, and `Queue` indeed uses a lock (named `self.mutex`): https://hg.python.org/cpython/file/3.4/Lib/queue.py#l38
`Queue.put_nowait()` acquires this lock, therefore it should not be used in the process callback.

The problem is that using `Queue` may look like a proper solution but it isn't.

I'd prefer to either show an actual solution (which turned out to be too complicated with `jack.RingBuffer`) or show an obviously bad (but very simple) solution and mention this fact in a comment.

Unless we find a simple way to do the former, we should do the latter.

**Comment by amstan** [comment]
> Queue.put_nowait() acquires this lock, therefore it should not be used in the process callback.

process() itself also aquires the GIL. Why are you not worried about that, but are worried about Queue?

**Comment by mgeier** [comment]
I *am* worried about it, but there is nothing I can do about it (except probably trying the GIL-less STM PyPy).

I'm worried about `Queue` because it might give a false sense of safety.
The example doesn't get any more useful/readable/understandable/safe/beautiful/... by using a `Queue` instead of naively using `print()`.

To make the limitations explicit, I created PR #18, what do you think about it?
