### ISSUE TITLE
Connect to client that run on remote machine

### ISSUE THREAD

**Issue by matansag** [spatialaudio/jackclient-python#41]
Hi, 
is there any way to connect to a client that run on different machine in the local-network? 
Or to run JACK-Client in Docker container while manipulating the jack connection on the host?

Thanks

**Comment by mgeier** [comment]
There are multiple ways to run JACK over a network, see http://www.jackaudio.org/faq/netjack.html.
I've never tried it myself, though.

**Comment by matansag** [comment]
thanks @mgeier 
i tried them, in jack.trip i can send audio to and from client but i can't modify client connections.
the same goes with netJACK2..

Maybe i missed something - i used netadapter and audioadapter

**Comment by mgeier** [comment]
Is this specific to the Python wrapper or is it a general JACK question?

If latter, you should probably ask at the JACK mailing list: http://www.jackaudio.org/community.html.

**Comment by jebofponderworthy** [comment]
Can you tell us a bit more of what you are trying to do?
