### ISSUE TITLE
How about optional parameters for JACK server name?

### ISSUE THREAD

**Issue by jebofponderworthy** [spatialaudio/jackclient-python#44]
Might we have JACK server name, as optional parameter for client object creation and references, instead of using environment variable $JACK_DEFAULT_SERVER ?

**Comment by mgeier** [comment]
Do you mean `jack.Client(name='myclient', servername='myserver')`?

http://jackclient-python.readthedocs.io/en/latest/#jack.Client

**Comment by jebofponderworthy** [comment]
That's it, thanks!!!
