### ISSUE TITLE
play audio in loop

### ISSUE THREAD

**Issue by redPanther** [spatialaudio/jackclient-python#50]
hi,
i want to play a wav file in a loop. 
I tried to modify playfile.py but without luck. My idea was to reset sndfile sf.seek(0) after all blocks put to queue.

any idea what's wrong?

**Comment by mgeier** [comment]
Using `sf.seek(0)` sounds like it could work. But if your audio file isn't huge, you could also load the whole file into memory (then you wouldn't even need a queue).

Either way, to know what's wrong, you'll have to show what you did!
