### ISSUE TITLE
dlopen issue on Windows 10 x64

### ISSUE THREAD

**Issue by iamluciano** [spatialaudio/jackclient-python#57]
Not working out of the box on Windows 10 x64, latest JACK and Python binary releases:

[Free Win10 VM from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
[JACK2 1.9.1 64 bit](
https://github.com/jackaudio/jackaudio.github.com/releases/download/1.9.11/Jack_v1.9.11_64_setup.exe)
[Python 3.7.0 x86-64](
https://www.python.org/ftp/python/3.7.0/python-3.7.0-amd64.exe)

Seems to be CFFI related, crash happens at jack.py line 45: `_lib = _ffi.dlopen(_libname)`

```
C:\Users\IEUser\Desktop\jackclient-python>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jack

(after a couple of seconds the Python shells exits with no error messages...)

C:\Users\IEUser\Desktop\jackclient-python>
```

Windows application log

```
Faulting application name: python.exe, version: 3.7.150.1013, time stamp: 0x5b331a30
Faulting module name: ntdll.dll, version: 10.0.17134.165, time stamp: 0xf4df6dc2
Exception code: 0xc0000026
Fault offset: 0x0000000000099968
Faulting process id: 0x1624
Faulting application start time: 0x01d434ca6ba235ee
Faulting application path: C:\Users\IEUser\AppData\Local\Programs\Python\Python37\python.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 5c6d9233-baba-4d47-aa17-64bf56997ebd
Faulting package full name: 
Faulting package-relative application ID: 
```

How can I contribute to further testing?

**Comment by mgeier** [comment]
Thanks for the report! Sadly, I don't have any idea what's going wrong here.

You could try it with different JACK versions.

And it would be interesting to see if other JACK-enabled applications work or if they show the same problem.

**Comment by lucianoiam** [comment]
Tried several binary versions of JACK at no avail. Solved this by compiling JACK from source using the Code::Blocks + MinGW workspace. Now jack-client works like a charm on Win10, thanks.

**Comment by Lieva** [comment]
Hi @lucianoiam 
I am currently trying to make jack-client work on Win10 as well and am running in the same issue you did. I was wondering if you could tell me more about how you fixed it? I have never worked with Code::Blocks before and have not yet done anything with c/c++ (what Code::Blocks is usually used for, if I understand correctly). So it would really help me a lot if you could describe in more detail what I can do to make it work.
Thank you in advance!

**Comment by sebistenzel** [comment]
@lucianoiam: I ran in the same issue, which version of JACK have you compiled? Seems the latest release are not building using windows.

**Comment by lucianoiam** [comment]
@sebistenzel I think it was 1.9.12 sorry I do not have that machine anymore. I wrote a guide to compile latest 1.9.14 using Windows + MinGW maybe that helps https://github.com/lucianoiam/jack2/blob/target-mingw/windows/README_MINGW . Beware the guide relies on my own fork but I think it is still possible to compile from the official source tree by disabling the metadata feature.

**Comment by sebistenzel** [comment]
@lucianoiam Thanks for your reply. Just found your fork and guide some minutes ago and started to dig into the details ... 
Will try to compile the official source based on your guide.
