### ISSUE TITLE
Question: xruns with 0ms delay

### ISSUE THREAD

**Issue by HaHeho** [spatialaudio/jackclient-python#66]
When I catch JACK xruns on certain clients via the API, what does it mean if the reported delay is 0ms?

**Comment by mgeier** [comment]
Sorry, I don't know. The delay value comes directly from the JACK library. You should probably ask on the JACK mailing list: http://jackaudio.org/community.html.

**Comment by HaHeho** [comment]
Okay, will do and report potential results. :)

**Comment by HaHeho** [comment]
My question does not seem to find anybody knowing more about this. :/

**Comment by mgeier** [comment]
I'm sorry your question (http://lists.jackaudio.org/pipermail/jack-devel-jackaudio.org/2019-May/001973.html) hasn't been answered (yet).

Maybe another option would be to try to ask on the "Linux Audio User" mailing list?

**Comment by mgeier** [comment]
@HaHeho Any news on this?
