### ISSUE TITLE
Can't import the module

### ISSUE THREAD

**Issue by fuzzysearch404** [spatialaudio/jackclient-python#84]
Hello.

Every time I try to import the `jack` module, Python crashes/exits.

I have installed:

1.  Jack library (via 64-bit Windows installer) I can run `jackd.exe`.
2.  This Jack client via pip. `pip install JACK-Client`.

Also can't find any errors/exceptions.

![image](https://user-images.githubusercontent.com/44381551/73838384-398c4680-481c-11ea-8576-8747a7f9845d.png)
![image](https://user-images.githubusercontent.com/44381551/73838388-3beea080-481c-11ea-8a61-ab4d34148865.png)

Am I doing something wrong or is that a bug? I have been trying to resolve this for about 2 hours, by trying different Python versions, this module versions (0.5.1, 0.5.0) etc. - could not find a solution on my own.

**Comment by HaHeho** [comment]
See https://github.com/spatialaudio/jackclient-python/issues/57.
