### ISSUE TITLE
access to transport position (jack_transport_query)

### ISSUE THREAD

**Issue by Vampouille** [spatialaudio/jackclient-python#9]
Hello, 
I would like to get current transport position from jack server. ffi string in jack.py contain reference to jack_transport_query() function but there is no corresponding python method : client.transport_query(). Did you plan to add this function ? I can help or test if you want...

Best, Vampouille

**Comment by Vampouille** [comment]
I try to add definition for structure _jack_position :

```c
struct _jack_position {
    jack_unique_t       unique_1; 
...
```
I also add definition for type used by _jack_position : jack_unique_t, jack_time_t, jack_nframes_t and jack_position_bits_t. finnaly, I wrote following method on Client python class :

```python
    def transport_query(self):
        """return current transport position."""
        position = _ffi.new("jack_position_t*")
        _lib.jack_transport_query(self._ptr, position)
        return position
```
transport_query() method return a <cdata 'jack_position_t *' owning 136 bytes> object

But this object does not have any value, all values are zero :

```python
position = client.transport_query()
print(position.unique_1)
print(position.bar)
print(position.beats_per_minute)
```
It always display 0

Do you known why _lib.jack_transport_query(self._ptr, position) call did not filled struct values ?

**Comment by Vampouille** [comment]
Finnaly with a complete jack setup (qtractor started and playing) it works, I can get all transport informations. I will make a fork and pull requests...

**Comment by mgeier** [comment]
Thanks for your interest in my little project!

> Did you plan to add this function ?

At some point, yes.
I guess I skipped it last time because the struct looked a bit complicated and I didn't want to spend too much time thinking about how to transform this to Python.

I'm looking forward to your PR!
